- name: Docker - Add {{ user_name }} to docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: true
  become: true


- name: Docker - Enable and start the docker daemon
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
    masked: false
  become: true
