- name: Setup default Git configuration
  git_config: name="{{ item.name }}" scope=global value="{{ item.value }}"
  with_items:
    - {name: user.name, value: "{{ git_user_name }}"}
    - {name: user.email, value: "{{ git_user_email }}"}
    - {name: core.editor, value: code}
  become_user: "{{ user_name }}"
  become: true