---
- name: Configure an ARCH based LINUX distribution (Manjaro for testing, Garuda for prod)
  hosts: all
  roles:
    - {role: core, tags: [core]}
    - {role: drivers, tags: [drivers, never]}
    - {role: developer, tags: [developer, never]}
    - {role: bash, tags: [bash, never]}
    - {role: fish, tags: [fish, never]}
    - {role: desktop, tags: [desktop, never]}
    - {role: security, tags: [security]}
    - {role: virtualization, tags: [virtualization, never]}
    - {role: cloud, tags: [cloud, never]}
    - {role: browsers, tags: [browsers]}
    - {role: media, tags: [media]}
    - {role: communicators, tags: [communicators]}
    - {role: tor, tags: [tor, never]}