---
- name: Configure an ARCH based LINUX distribution (Manjaro for testing, Garuda for prod)
  hosts: all
  roles:
    - {role: core, tags: [core]}
    - {role: drivers, tags: [drivers]}
    # - {role: security, tags: [security]}
    # - {role: virtualization, tags: [virtualization]}
    # - {role: de, tags: [virtualization]}
    # - {role: browsers, tags: [browsers]}
    # - {role: communicators, tags: [communicators]}
    # - {role: media, tags: [media]}
    # - {role: tor, tags: [tor, never]}

  handlers:
    - import_tasks: handlers/os-restart.yml
    - import_tasks: handlers/freshclam.yml
