- name: Install desktop pakages - YAY
  yay:
    name: "{{desktop}}"
    state: present
  become: true


- name: Copy konsaves profiles
  copy: 
    src: "{{ item }}"
    dest: /home/{{ user_name }}/.config/konsave/profiles/
    mode: 0777
  with_fileglob: 
    - ../files/konsave/*
  become: yes
  become_user: "{{ user_name }}"


- name: Apply konsave settings (MUST RESTART/LOG OUT AFTERWARDS !!!)
  shell: konsave -a {{ konsave_profile }}
  become_user: "{{ user_name }}"
  become: true


- name: Copy conky settings
  copy: 
    src: "{{ item }}"
    dest: /home/{{ user_name }}/.config/conky/
    mode: 0777
  with_fileglob: 
    - ../files/conky/*
  become: yes
  become_user: "{{ user_name }}"
  