- name: Install desktop pakages - YAY
  yay:
    name: "{{desktop}}"
    state: present
  become: true


- name: Copy konsaves profiles
  copy: 
    src: ../files/konsave/
    dest: /home/{{ user_name }}/.config/konsave/profiles/
    mode: 0777
  become: yes
  become_user: "{{ user_name }}"


- name: Apply konsave settings (MUST RESTART/LOG OUT AFTERWARDS !!!)
  shell: konsave -a {{ konsave_profile }}
  become_user: "{{ user_name }}"
  become: true


- name: Copy conky settings
  copy: 
    src: "{{ item }}"
    dest: /home/{{ user_name }}/.config/conky/
    mode: 0777
  with_fileglob: 
    - ../files/conky/*
  become: yes
  become_user: "{{ user_name }}"

- name: Copy conky autostart job
  copy: 
    src: "{{ item }}"
    dest: /home/{{ user_name }}/.config/autostart/
    mode: 0777
  with_fileglob: 
    - ../files/conky.desktop
  become: yes
  become_user: "{{ user_name }}"


- name: Add executable line to conky.desktop job
  lineinfile:
    path: /home/{{ user_name }}/.config/autostart/conky.desktop
    line: Exec=sh /home/{{ user_name }}/.config/conky/startup-conky.sh
  become: true 