---

- name: Update cache and upgrade - PACMAN
  block:
    - name: Update and upgrade pacman
      community.general.pacman:
        update_cache: true
        upgrade: true
        upgrade_extra_args: --noconfirm
      become: true
      tags:
        - update_and_upgrade_pacman

  rescue:
    - name: RESCUE - Remove pacman db lock
      command: rm /var/lib/pacman/db.lck
      become: true
    - name: Update and upgrade pacman - second try after rescue
      community.general.pacman:
        update_cache: true
        upgrade: true
        upgrade_extra_args: --noconfirm
      become: true


- name: Install Core Utils
  community.general.pacman:
    name: "{{ core_utils }}"
    state: present
  become: true