- name: Update cache and upgrade - PACMAN
  block:
    - name: Update and upgrade - PACMAN
      community.general.pacman:
        update_cache: true
        upgrade: true
        upgrade_extra_args: --noconfirm
      become: true
      tags:
        - update_and_upgrade
        - always

  rescue:
    - name: RESCUE - Remove pacman db lock
      command: rm /var/lib/pacman/db.lck
      become: true
    - name: Update and upgrade - PACMAN - second try after rescue
      community.general.pacman:
        update_cache: true
        upgrade: true
        upgrade_extra_args: --noconfirm
      become: true


- name: Install Core Utils - PACMAN
  community.general.pacman:
    name: "{{ core_utils }}"
    state: present
  become: true

- name: Update cache and upgrade - YAY with AUR
  yay:
    update_cache: true
    upgrade: true
  become: true
  register: yay_update_output
  changed_when: "'Package DB up-to-date' not in yay_update_output.msg"
  tags:
    - update_and_upgrade
    - always

- name: Install Core Utils - YAY
  yay:
    name: "{{other_core_utils}}"
  become: true

