- name: Install tor browser, required dependencies and tools - YAY
  yay:
    name: "{{tor}}"
    state: present
  become: true

- name: Configure nordvpn
  shell: |
    usermod -aG nordvpn $USER
    systemctl start nordvpnd
  become_user: "{{ user_name }}"
  become: true